"use client"
export const metadata = {
    title: 'Add Friend | Dashboard | PicxaBee',
    description: 'Generated by create next app',
  }

const AddFriendPage = () => {
    return (
        <div>
           <h2>This is add Friend Page</h2> 
        </div>
    );
};

export default AddFriendPage;